### ISSUE TITLE
211214 코드리뷰(2) class, css 작업

### ISSUE THREAD

**Issue by nurimeansworld** [nurimeansworld/clone_starbucks#4]
코드리뷰 여기에 코멘트로 남겨주시면 감사하겠습니다..!! 🙇 
URL : https://nurimeansworld.github.io/clone_starbucks/html/food_list.html

**Comment by tood21** [comment]
https://github.com/nurimeansworld/clone_starbucks/blob/4f09cbb1da8fe763aa440053d6aa0e88cc36d082/css/style.css#L42-L43

- 좌우 마진을 px로 주신 이유가 궁금합니다.

- 메뉴의 클릭 범위(?)가 조금 더 크면 좋을 듯 합니다.

**Comment by nurimeansworld** [comment]
완료하여 close 합니다 🙏
