### ISSUE TITLE
211219 코드리뷰(3) css 나머지 전부

### ISSUE THREAD

**Issue by nurimeansworld** [nurimeansworld/clone_starbucks#5]
코드리뷰 여기에 코멘트로 남겨주시면 감사하겠습니다..!! 🙇
URL : https://nurimeansworld.github.io/clone_starbucks/html/food_list.html

## CHECK::
- font color는 반드시 해당하는 태그에 직접 설정해줘야 하는지
  - a 태그, input 태그 는 상속이 되지 않아서 따로 되지 않는 것이 맞고 다른 태그 확인해보기
  - font-family, color는 직접적인 해당 태그에 설정을 해줘야 정확하게 적용 가능
- 다들 체크박스 스타일링 어떻게 하실 생각이신지 궁금합니다
- .product-accordion 에 padding 값 bottom만 안주신 이유(스벅 페이지도 안되어있길래 궁금)
- media query break point
  - all 반응형이 아닌 이상 PC, MO 

## 아직 구현 안된 부분 (TODO::)
- 서브 메뉴 hover 효과
- nav-tap 다시 되게 설정!
- 상세분류 셀렉트 박스 css
- 분류보기 > 카테고리 > 체크박스 css
- media query
- 통합검색

**Comment by tood21** [comment]
https://github.com/nurimeansworld/clone_starbucks/blob/896166f6bb7e961eae0b970973cd4f6fe1873d67/html/food_list.html#L31-L36
* 중간에 구분선이 안보입니다.

https://github.com/nurimeansworld/clone_starbucks/blob/896166f6bb7e961eae0b970973cd4f6fe1873d67/html/food_list.html#L104-L111
* 라벨에 cursor: point 해주시면 더 좋을 듯 합니다.

**Comment by nurimeansworld** [comment]
(메모)
웹접근성 측면으로 hover했을 때 내가 어디에 있는지 표시하는 게 좋다!
id class 명 주는 기준
id는 section이나 대분류를 나누는 기준으로 값을 준다.
class는 media query로만 보이는 부분엔 앞에 media_클래스명 이렇게 넣기도!

**Comment by nurimeansworld** [comment]
[wiki 211219](https://github.com/nurimeansworld/clone_starbucks/wiki/211219-%EC%BD%94%EB%93%9C%EB%A6%AC%EB%B7%B0-%EC%A0%95%EB%A6%AC-%EB%B0%8F-%ED%9A%8C%EA%B3%A0)에 정리 및 코드 수정 완료하였으므로 close 합니다 🙏
